# Generated by Django 2.2.15 on 2020-09-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(max_length=100)),
                ('mean', models.TextField(max_length=200)),
                ('Toeic', models.BooleanField()),
                ('Opic', models.BooleanField()),
                ('korean_SAT', models.BooleanField()),
            ],
        ),
    ]
