# Generated by Django 2.2.15 on 2020-09-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_listening_speaking'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='phonetic_symbols',
            field=models.TextField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
