# Generated by Django 2.2.15 on 2020-09-28 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200915_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datecount',
            old_name='text_speak_count',
            new_name='vocabulary_count',
        ),
    ]
